disable closure compiler because it breaks build
and satori throws next error:
```
TypeError: c[(p + 1)].Eb is not a function
 ❯ yoga-wasm-web/dist/yoga.mjs:67:295
 ❯ _ yoga-wasm-web/dist/yoga.mjs:66:504
 ❯ W.<anonymous> yoga-wasm-web/dist/yoga.mjs:40:52
 ❯ W.<anonymous> yoga-wasm-web/dist/entry.js:1:4518
 ❯ O.E.<computed> [as calculateLayout] yoga-wasm-web/dist/entry.js:1:3108
 ❯ Module.satori src/satori.ts:160:7
```